# Generated by Django 4.0.6 on 2022-08-12 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('animaLibApp', '0002_animations_saved_animation_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animations',
            name='animation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
